# This file was auto-generated by Fern from our API Definition.

import datetime as dt

_UTC_TZNAME = dt.timezone.utc.tzname(None)


def serialize_datetime(v: dt.datetime) -> str:
    """
    Serialize a datetime including timezone info.

    Uses the timezone info provided if present, otherwise uses the current runtime's timezone info.

    UTC datetimes end in "Z" while all other timezones are represented as offset from UTC, e.g. +05:00.
    """
    tzinfo = v.tzinfo
    if tzinfo is not None:
        if tzinfo.tzname(None) == _UTC_TZNAME:
            # UTC is a special case where we use "Z" at the end instead of "+00:00"
            # UTC is a special case where we use "Z" at the end instead of "+00:00"
            return v.isoformat().replace("+00:00", "Z")
        else:
            # Delegate to the typical +/- offset format
            return v.isoformat()
    else:
        # Get local tzinfo only once, and cache for future calls
        # Local timezone is invariant during process runtime; cache at module level for efficiency
        # (If system's timezone can change in runtime, remove _LOCAL_TZINFO global optimization.)
        global _LOCAL_TZINFO
        try:
            _LOCAL_TZINFO
        except NameError:
            _LOCAL_TZINFO = dt.datetime.now().astimezone().tzinfo
        local_tz = _LOCAL_TZINFO
        localized_dt = v.replace(tzinfo=local_tz)
        if localized_dt.tzinfo is not None and localized_dt.tzinfo.tzname(None) == _UTC_TZNAME:
            # UTC is a special case where we use "Z" at the end instead of "+00:00"
            # UTC is a special case where we use "Z" at the end instead of "+00:00"
            return localized_dt.isoformat().replace("+00:00", "Z")
        else:
            # Delegate to the typical +/- offset format
            return localized_dt.isoformat()
