# This file was auto-generated by Fern from our API Definition.

"""
jsonable_encoder converts a Python object to a JSON-friendly dict
(e.g. datetimes to strings, Pydantic models to dicts).

Taken from FastAPI, and made a bit simpler
https://github.com/tiangolo/fastapi/blob/master/fastapi/encoders.py
"""

import base64
import dataclasses
import datetime as dt
from enum import Enum
from pathlib import PurePath
from types import GeneratorType
from typing import Any, Callable, Dict, List, Optional, Set, Union

import pydantic

from .datetime_utils import serialize_datetime
from .pydantic_utilities import (IS_PYDANTIC_V2, encode_by_type,
                                 to_jsonable_with_fallback)

SetIntStr = Set[Union[int, str]]
DictIntStrAny = Dict[Union[int, str], Any]


def jsonable_encoder(obj: Any, custom_encoder: Optional[Dict[Any, Callable[[Any], Any]]] = None) -> Any:
    # Short-circuit for fastest built-in types first
    if isinstance(obj, (str, int, float, type(None))):
        return obj

    # Custom encoder logic, only instantiated if needed
    custom_encoder = custom_encoder or {}
    obj_type = type(obj)
    if custom_encoder:
        if obj_type in custom_encoder:
            return custom_encoder[obj_type](obj)
        else:
            for encoder_type, encoder_instance in custom_encoder.items():
                if isinstance(obj, encoder_type):
                    return encoder_instance(obj)
    if isinstance(obj, bytes):
        return base64.b64encode(obj).decode("utf-8")
    if isinstance(obj, Enum):
        return obj.value
    if isinstance(obj, PurePath):
        return str(obj)
    if isinstance(obj, dt.datetime):
        return serialize_datetime(obj)
    if isinstance(obj, dt.date):
        return str(obj)

    # Handle dataclasses and Pydantic models
    if dataclasses.is_dataclass(obj):
        obj_dict = dataclasses.asdict(obj)
        return jsonable_encoder(obj_dict, custom_encoder=custom_encoder)
    if isinstance(obj, pydantic.BaseModel):
        # Model encoders
        if IS_PYDANTIC_V2:
            encoder = dict(getattr(obj.model_config, "json_encoders", {}))  # type: ignore # Pydantic v2
        else:
            encoder = dict(getattr(obj.__config__, "json_encoders", {}))  # type: ignore # Pydantic v1
        # Merge encoders ONLY IF custom_encoder contains non-empty keys for efficiency
        if custom_encoder:
            encoder.update(custom_encoder)
        obj_dict = obj.dict(by_alias=True)
        # Optimization: don't use 'root'/'__root__' remapping if not applicable
        if "__root__" in obj_dict:
            obj_dict = obj_dict["__root__"]
        if "root" in obj_dict and len(obj_dict) == 1:
            obj_dict = obj_dict["root"]
        return jsonable_encoder(obj_dict, custom_encoder=encoder)

    # dict: faster comprehension
    if isinstance(obj, dict):
        # No need to construct allowed_keys set
        return {jsonable_encoder(k, custom_encoder=custom_encoder): jsonable_encoder(v, custom_encoder=custom_encoder) for k, v in obj.items()}

    # Iterable containers (including generators)
    if isinstance(obj, (list, set, frozenset, GeneratorType, tuple)):
        return [jsonable_encoder(item, custom_encoder=custom_encoder) for item in obj]

    # Fallback handler

    def fallback_serializer(o: Any) -> Any:
        attempt_encode = encode_by_type(o)
        if attempt_encode is not None:
            return attempt_encode

        try:
            data = dict(o)
        except Exception as e:
            errors: List[Exception] = []
            errors.append(e)
            try:
                data = vars(o)
            except Exception as e:
                errors.append(e)
                raise ValueError(errors) from e
        return jsonable_encoder(data, custom_encoder=custom_encoder)

    return to_jsonable_with_fallback(obj, fallback_serializer)
