# This file was auto-generated by Fern from our API Definition.

"""
jsonable_encoder converts a Python object to a JSON-friendly dict
(e.g. datetimes to strings, Pydantic models to dicts).

Taken from FastAPI, and made a bit simpler
https://github.com/tiangolo/fastapi/blob/master/fastapi/encoders.py
"""

import base64
import dataclasses
import datetime as dt
from enum import Enum
from pathlib import PurePath
from types import GeneratorType
from typing import Any, Callable, Dict, List, Optional, Set, Union

import pydantic
from .datetime_utils import serialize_datetime
from .pydantic_utilities import (
    IS_PYDANTIC_V2,
    encode_by_type,
    to_jsonable_with_fallback,
)

SetIntStr = Set[Union[int, str]]
DictIntStrAny = Dict[Union[int, str], Any]


def jsonable_encoder(obj: Any, custom_encoder: Optional[Dict[Any, Callable[[Any], Any]]] = None) -> Any:
    # Move primitive type fast-path to the top for quick return.
    if isinstance(obj, (str, int, float, type(None))):
        return obj

    # Pre-initialize to empty dict only if needed
    custom_encoder = custom_encoder or {}
    if custom_encoder:
        obj_type = type(obj)
        encoder_func = custom_encoder.get(obj_type)
        if encoder_func is not None:
            return encoder_func(obj)
        for encoder_type, encoder_instance in custom_encoder.items():
            if isinstance(obj, encoder_type):
                return encoder_instance(obj)

    # Fast-path for Pydantic model (rare path; in practice, usually primitives or list/dict)
    if isinstance(obj, pydantic.BaseModel):
        if IS_PYDANTIC_V2:
            base_encoders = getattr(obj.model_config, "json_encoders", {})  # type: ignore # Pydantic v2
        else:
            base_encoders = getattr(obj.__config__, "json_encoders", {})  # type: ignore # Pydantic v1
        # Merge the base encoder and custom encoder with priority to custom_encoder in a new dict
        if base_encoders or custom_encoder:
            merged_encoders = base_encoders.copy()
            merged_encoders.update(custom_encoder)
        else:
            merged_encoders = {}
        obj_dict = obj.dict(by_alias=True)
        # Only one root extraction is ever relevant; no need to check both if matched once
        if isinstance(obj_dict, dict):
            if "__root__" in obj_dict:
                obj_dict = obj_dict["__root__"]
            elif "root" in obj_dict:
                obj_dict = obj_dict["root"]
        return jsonable_encoder(obj_dict, custom_encoder=merged_encoders)

    # Dataclass handling
    if dataclasses.is_dataclass(obj):
        obj_dict = dataclasses.asdict(obj)  # type: ignore
        return jsonable_encoder(obj_dict, custom_encoder=custom_encoder)
    if isinstance(obj, bytes):
        return base64.b64encode(obj).decode("utf-8")
    if isinstance(obj, Enum):
        return obj.value
    if isinstance(obj, PurePath):
        return str(obj)
    if isinstance(obj, dt.datetime):
        return serialize_datetime(obj)
    if isinstance(obj, dt.date):
        return str(obj)
    if isinstance(obj, dict):
        # Minor optimization: dict comprehension is usually fastest in CPython
        return {
            jsonable_encoder(key, custom_encoder=custom_encoder):
            jsonable_encoder(value, custom_encoder=custom_encoder)
            for key, value in obj.items()
        }

    # List/set/tuple/versioned generator handling
    if isinstance(obj, (list, set, frozenset, GeneratorType, tuple)):
        # List comprehension is more efficient in CPython than manual append + for
        return [
            jsonable_encoder(item, custom_encoder=custom_encoder)
            for item in obj
        ]


    def fallback_serializer(o: Any) -> Any:
        attempt_encode = encode_by_type(o)
        if attempt_encode is not None:
            return attempt_encode

        # Try attribute access first to avoid exception cost if the object is dict-like or has __dict__
        data = None
        if hasattr(o, "__dict__"):
            try:
                data = vars(o)
            except Exception:
                pass
        if data is None:
            # Try dict casting (as last resort)
            try:
                data = dict(o)
            except Exception as e1:
                errors: List[Exception] = [e1]
                try:
                    data = vars(o)
                except Exception as e2:
                    errors.append(e2)
                    raise ValueError(errors) from e2
        return jsonable_encoder(data, custom_encoder=custom_encoder)

    return to_jsonable_with_fallback(obj, fallback_serializer)
