# This file was auto-generated by Fern from our API Definition.

from typing import Any, Dict, List, Optional, Tuple

import pydantic


# Flattens dicts to be of the form {"key[subkey][subkey2]": value} where value is not a dict
def traverse_query_dict(dict_flat: Dict[str, Any], key_prefix: Optional[str] = None) -> List[Tuple[str, Any]]:
    result = []
    for k, v in dict_flat.items():
        key = f"{key_prefix}[{k}]" if key_prefix is not None else k
        if isinstance(v, dict):
            result.extend(traverse_query_dict(v, key))
        elif isinstance(v, list):
            for arr_v in v:
                if isinstance(arr_v, dict):
                    result.extend(traverse_query_dict(arr_v, key))
                else:
                    result.append((key, arr_v))
        else:
            result.append((key, v))
    return result


def single_query_encoder(query_key: str, query_value: Any) -> List[Tuple[str, Any]]:
    # Use local variables for fast lookup of often-used functions
    isinstance_ = isinstance
    BaseModel = pydantic.BaseModel

    # Single isinstance() check instead of two, for pydantic.BaseModel | dict scenario
    if isinstance_(query_value, BaseModel):
        obj_dict = query_value.dict(by_alias=True)
        return traverse_query_dict(obj_dict, query_key)
    elif isinstance_(query_value, dict):
        return traverse_query_dict(query_value, query_key)
    elif isinstance_(query_value, list):
        encoded_values: List[Tuple[str, Any]] = []
        append = encoded_values.append
        extend = encoded_values.extend
        for value in query_value:
            if isinstance_(value, BaseModel):
                obj_dict = value.dict(by_alias=True)
                extend(traverse_query_dict(obj_dict, query_key))
            elif isinstance_(value, dict):
                extend(traverse_query_dict(value, query_key))
            else:
                append((query_key, value))

        return encoded_values

    return [(query_key, query_value)]


def encode_query(query: Optional[Dict[str, Any]]) -> Optional[List[Tuple[str, Any]]]:
    if query is None:
        return None

    encoded_query: List[Tuple[str, Any]] = []
    extend = encoded_query.extend
    for k, v in query.items():
        extend(single_query_encoder(k, v))
    return encoded_query
