# This file was auto-generated by Fern from our API Definition.

from typing import Any, Dict, Mapping, Optional


def remove_none_from_dict(original: Mapping[str, Optional[Any]]) -> Dict[str, Any]:
    # Use dict comprehension for minimal allocation
    return {k: v for k, v in original.items() if v is not None}
